### ISSUE TITLE
Duplicate toolbar item exception when not duplicated.

### ISSUE THREAD

**Issue by twinj** [PSPDFKit/Cordova-iOS#31] opened 2017-05-17 01:21 UTC
When attempting to change the default toolbar layout PSPDFKitPlugin crashes with the below exception.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The set leftBarButtonItems contains items already present in rightBarButtonItems of the same view mode. Remove duplicate items from rightBarButtonItems first.'

Using:

```
PSPDFKitPlugin.setOptions({
      pageTransition: 'curl',
      backgroundColor: 'white',
      // Close gets duplicated in 6
      leftBarButtonItems: ['bookmark', 'search'],
      // View mode no longer works
      rightBarButtonItems: ['annotation'],
    });
```

It seems to me that changes in the main library are not currently properly propagated to this plugin? E.g: Version 5 works perfectly. Then in early version 6 the close menu gets duplicated if I manually add it to the left menu.

Version 6.5 creates issues with the newer viewMode support.

How do I know which revision to use with which version to get the best support?

**Comment by steipete** [comment] 2017-05-18 16:14
As a workaround, you likely can set `leftBarButtonItems: []`, rightBarButtonItems: []` so the toolbar is cleared before adding buttons again - we added safeguards that make sense in most cases but are disruptive here in Cordova configuration. We'll get that fixed up.

**Comment by twinj** [comment] 2017-05-19 06:07
I tried the workaround using the setLeft and setRight functions. No luck.

I have also updated from 6.6.1 to 6.7.0 and get the same error.

**Comment by steviki** [comment] 2017-05-19 10:58
Hi @twinj,

We are always trying to keep the Cordova plugin updated to work with the current available PSPDFKit for iOS release.

We fixed the close button showing up twice when added manually already: https://github.com/PSPDFKit/Cordova-iOS/commit/27bf20785436d3bc5d72f1deb7b442e54ca92e20

The issue here is that the options passed to the `present` method are ordered alphabetically when parsed, therefore `leftBarButtonItems` is always set before `rightBarButtonItems`, while `rightBarButtonItems` still has the default values and therefore the exception happens.  Also adding duplicate options like `leftBarButtonItems: []` doesn’t work, as only the last passed option from duplicate keys in the dictionary is preserved and set.

You can use the following code to set the buttons in the correct order:

```
PSPDFKitPlugin.present('pdf/PSPDFKit 6 QuickStart Guide.pdf', {
    pageTransition : 'curl',
    backgroundColor: 'white',
});
PSPDFKitPlugin.setRightBarButtonItems(['annotation']);
PSPDFKitPlugin.setLeftBarButtonItems(['bookmark', 'search']);
```

Let us know if that works for you.

**Comment by twinj** [comment] 2017-05-22 00:04
Same problem.

**Comment by steviki** [comment] 2017-05-24 08:19
Interesting. 
Please note that the order of the calls is important; set the right bar buttons first and then the left ones. That's because you first need to override the default items for the right side, so the items are not duplicated when setting the left items.

You can also try resetting the items on both sides beforehand and only then set your desired items.

```
PSPDFKitPlugin.setRightBarButtonItems([]);
PSPDFKitPlugin.setLeftBarButtonItems([]);
PSPDFKitPlugin.setRightBarButtonItems(['annotation']);
PSPDFKitPlugin.setLeftBarButtonItems(['bookmark', 'search']);
```

If that still gives you trouble, please send us a runnable sample project over via [our support desk](https://pspdfkit.com/support/request) so we can take a closer look what's up there.
Thanks.

**Comment by twinj** [comment] 2017-05-24 08:23
You can't recreate the problem with the sample app?

**Comment by steviki** [comment] 2017-05-24 08:26
I can reproduce the original issue when settings the bar buttons via the options:

```
PSPDFKitPlugin.setOptions({
    pageTransition: 'curl',
    backgroundColor: 'white',
    leftBarButtonItems: ['bookmark', 'search'],
    rightBarButtonItems: ['annotation'],
});
```

Although, using the dedicated setters seems to work fine:

```
PSPDFKitPlugin.present('pdf/PSPDFKit 6 QuickStart Guide.pdf', {
    pageTransition : 'curl',
    backgroundColor: 'white',
});
PSPDFKitPlugin.setRightBarButtonItems(['annotation']);
PSPDFKitPlugin.setLeftBarButtonItems(['bookmark', 'search']);
```

Can you verify that this is the case for you as well?

**Comment by twinj** [comment] 2017-06-05 04:11
// Before changing
[Debug] Items – [["close"], ["search", "outline", "thumbnails"]] (2) (ion-dev.js, line 156)

// After clearing and changing using setter. I first clear.
[Debug] Items – [["bookmark", "search"], ["annotation"]] (2) (ion-dev.js, line 156)

Then when I open in another page using present I still get the error.

If I set the items each time I open the document its fine? 

Any insight on this behavior?

**Comment by steviki** [comment] 2017-06-07 09:43
This has now been fixed in https://github.com/PSPDFKit/Cordova-iOS/commit/aeffa174e29237abb47eb5107789fe690a432b8d.

Existing bar button items are now reset if both left and right bar button items are set simultaneously.

Thanks for reporting this @twinj.

**Closed by steviki** 2017-06-07 09:43 UTC
